import type { Metadata } from 'next';
import { Sarabun } from 'next/font/google';

import './globals.css';
const sarabun = Sarabun({
    subsets: ['latin'],
    variable: '--font-sarabun',
    display: 'swap',
    weight: ['100', '300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${sarabun.variable} antialiased`}>{children}</body>
        </html>
    );
}
