import { Mulish } from "next/font/google";
import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { setRequestLocale } from "next-intl/server";
import { routing } from "@/i18n/routing";
import { Toaster } from "@/components/ui/toaster";
import Providers from "./../../components/providers/index";
import Footer from "../components/footer";
import Header from "../components/header";

// Fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const zain = localFont({
  src: "./fonts/Zain-Regular.ttf",
  variable: "--font-zain",
  weight: "100 900",
});
const mulish = Mulish({
  subsets: ["latin"],
  variable: "--font-mulish",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

//Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// Generate all possible locale-based route parameters for Next.js to pre-render at build time
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({ children, params }: LayoutProps) {
  const { locale } = params;
  // Enable static rendering
  setRequestLocale(locale);
  if (!hasLocale(routing.locales, locale)) {
    return notFound();
  }

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${zain.variable} ${mulish.className} antialiased selection:bg-maroon-600 selection:text-white dark:bg-zinc-800`}
      >
        {/* Providers */}
        <Providers>
          {/* Header  */}
          <Header />

          {/* Main content */}
          <main className="font-sarabun container mx-auto  w-full min-h-[calc(100vh-200px)] px-20">
            {/* Main children components */}
            {children}

            {/* Toast notifications */}
            <Toaster />
          </main>

          {/* Footer */}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
