import { hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import Providers from './../../components/providers/index';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { getLocale, getMessages, getNow, getTimeZone, setRequestLocale } from 'next-intl/server';
import Header from './../../components/layout/header/header';

// Fonts
const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

const zain = localFont({
    src: './fonts/Zain-Regular.ttf',
    variable: '--font-zain',
    weight: '100 900',
});

//Metadata
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
// Generate all possible locale-based route parameters for Next.js to pre-render at build time
export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({ children, params: { locale } }: LayoutProps) {
    //Translation
    const intlLocale = await getLocale();
    const messages = await getMessages();
    const now = await getNow();
    const timeZone = await getTimeZone();
    // Enable static rendering
    setRequestLocale(locale);
    if (!hasLocale(routing.locales, locale)) {
        return notFound();
    }

    return (
        <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
            <body className={`${geistSans.variable} ${geistMono.variable} ${zain.variable} antialiased`}>
                <Providers locale={intlLocale} messages={messages} now={now} timeZone={timeZone}>
                    <Header />

                    {/*//Main  */}
                    {children}

                    {/* //todo footer  */}
                </Providers>
            </body>
        </html>
    );
}
